### ISSUE TITLE
Cannot use at swift  3 / 4

### ISSUE THREAD

**Issue by eplnh** [DevFatani/Web_Vuw#2]
/Users/ekoprasetyo/flutter/.pub-cache/hosted/pub.dartlang.org/web_vuw-0.1.6/ios/Classes/WebVuwPlugin.m:2:9: 'web_vuw/web_vuw-Swift.h' file not found

**Comment by DevFatani** [comment]
did you install pod?
open terminal
go to your project and  **ios** dir and then `pod install` and then` pod update`

**Comment by eplnh** [comment]
@DevFatani  I'm sorry when I tried to create a new project with this package everything works fine.
But when I add this plugin to the existing project, it didn't work.

And. How to use "controller.loadurl("url");" properly ?
because I use this
```
return FutureBuilder<WebVuwController>(
      future: _controller.future,
      builder: (context, snapshot) {
        final webViewReady = snapshot.connectionState == ConnectionState.done;
        final controller = snapshot.data;

        if (webViewReady) {
          _ssWebVuwEvents = controller.onEvents().listen((events) {
            print('Events => $events');
          });
          if (url != "") controller.loadUrl(url);
        }

        return Scaffold(
        . . . . .
```

it works but always shows this error
```
Failed to cancel existing stream: stream_fail. could not streaming ((null))
[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method loadUrl on channel plugins.devfatani.com/web_vuw_0)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      WebVuwController.loadUrl (package:web_vuw/web_vuw.dart:28:21)
<asynchronous suspension>
#2      _HomeScreenState.build.<anonymous closure> (package:lta_ios/screens/home_screen.dart:69:37)
#3      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:691:20)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
#17     _invoke (dart:ui/hooks.dart:173:13)
#18     _drawFrame (dart:ui/hooks.dart:162:3)
```

when I move to another page, it's working fine but shows this error.

```
Failed to cancel existing stream: stream_fail. could not streaming ((null))
[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method loadUrl on channel plugins.devfatani.com/web_vuw_0)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
Reloaded 8 of 559 libraries in 2,099ms.
#1      WebVuwController.loadUrl (package:web_vuw/web_vuw.dart:28:21)
<asynchronous suspension>
#2      _HomeScreenState.build.<anonymous closure> (package:lta_ios/screens/home_screen.dart:69:37)
#3      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#11     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
#24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#60     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#66     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#70     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#76     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#80     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
#81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:691:20)
#82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
#83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
#86     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#87     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#88     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#89     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Thank you.
